# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/my-haiku',
                'doc_host': 'https://stephenjfox.github.io',
                'git_url': 'https://github.com/stephenjfox/my-haiku',
                'lib_path': 'my_haiku'},
  'syms': {'my_haiku.core': {'my_haiku.core.foo': ('core.html#foo', 'my_haiku/core.py')}}}
