# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_basics.ipynb.

# %% auto 0
__all__ = ['current_params', 'transform', 'get_param', 'linear']

# %% ../nbs/01_basics.ipynb 2
"""global state for tracking parameters"""
current_params = []

# %% ../nbs/01_basics.ipynb 3
def transform(func):

    def apply_f(params, *args, **kwargs):
        current_params.append(params)
        outs = func(*args, **kwargs)
        current_params.pop()
        return outs
    return apply_f

# %% ../nbs/01_basics.ipynb 4
def get_param(identifier):
    "Get a parameter from the global state"
    # NOTE: ONLY WORKS WITH OUR push-pop implementation
    return current_params[-1][identifier]

# %% ../nbs/01_basics.ipynb 10
import jax
import jax.numpy as jnp

def linear(x):
    return x @ get_param('w') + get_param('b')
